---
- name: find a process and kill
  hosts: 192.168.1.156

  tasks:
  - name: get running process from host
    ignore_errors: yes
    shell: "ps -few | grep top | awk '{print $2}'"
    register: running_process

  - name: kill running processes
    ignore_errors: yes
    shell: "kill {{ item }}"
    with_items: "{{ running_process.stdout_lines }}"

