---
- name: installing and running apache
  hosts: localhost

  tasks:
  - name: install apache
    yum:
     name: httpd
     state: present
  - name: start httpd
    service:
     name: httpd
     state: started
